#!/bin/bash
echo "[ .. ] > Generiere UPDATE-Datei ..."

cd /var/www/wim/
TIMESTAMP=`date -u +%s`
echo $TIMESTAMP >| UPDATE

echo "[ OK ] > Fertig."

# Das ganze hier unten ist obsolet, da das ganze WIM von Github gezogen wird.

exit 0;

oldRev=$(<cli-revision)
newRev=`expr $oldRev + 1`
VERSION=$(<cli-version)
echo "$newRev" >| cli-revision 
cd ../

genString="{"

# Metadaten generieren

TIMESTAMP=`date -u +%s`
REV=$newRev

echo "       > TIMESTAMP: $TIMESTAMP"
echo "       > VERSION: $VERSION"
echo "       > REVISION: $REV"

genString+="\"version\":$VERSION,"
genString+="\"revision\":$REV,"
genString+="\"timestamp\":\"$TIMESTAMP\","
genString+="\"workdir\":["

# Arbeitsbereich überprüfen

echo "       > Überprüfe Arbeitsbereich ..."
first=1

for f in `find ./ -type f -not -path "*/.git*" -not -path "*/.vscode*" -not -name "UPDATE" -printf '%P\n'`; do
    if [ "$first" -eq "0" ]; then
        genString+=","
    fi

    modified=`date -u -r $f +%s`

    genString+="{\"path\":\"$f\","
    genString+="\"changed\":\"$modified\"}"

    first=0
done

genString+="]}"

echo $genString >| UPDATE

echo "[ OK ] > Fertig."